# Generated by Django 4.1 on 2023-03-21 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'doctors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatientContact',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, null=True)),
                ('street_address', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('zip', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'patient_contact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatientDoctors',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'patient_doctors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatientId',
            fields=[
                ('patient_id', models.AutoField(db_column='Patient_ID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='Firstname', max_length=255, null=True)),
                ('lastname', models.CharField(db_column='Lastname', max_length=255, null=True)),
                ('dob', models.DateField(db_column='DOB', null=True)),
                ('age', models.IntegerField(db_column='Age', max_length=255, null=True)),
                ('biol_sex', models.CharField(db_column='Biol_sex', max_length=255, null=True)),
                ('ethnicity', models.CharField(db_column='Ethnicity', max_length=255, null=True)),
            ],
            options={
                'db_table': 'patient_id',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatientFinance',
            fields=[
                ('patient', models.OneToOneField(db_column='Patient_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='web_app.patientid')),
                ('amount_due', models.DecimalField(db_column='Amount_due', decimal_places=5, max_digits=10, null=True)),
                ('ins_co', models.CharField(db_column='Ins_co', max_length=255, null=True)),
            ],
            options={
                'db_table': 'patient_finance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatientHealth',
            fields=[
                ('patient', models.OneToOneField(db_column='Patient_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='web_app.patientid')),
                ('current_smoker', models.BooleanField(db_column='Current_smoker', null=True)),
                ('condition_1', models.CharField(db_column='Condition_1', max_length=255, null=True)),
                ('condition_2', models.CharField(db_column='Condition_2', max_length=255, null=True)),
                ('condition_3', models.CharField(db_column='Condition_3', max_length=255, null=True)),
                ('condition_4', models.CharField(db_column='Condition_4', max_length=255, null=True)),
                ('condition_5', models.CharField(db_column='Condition_5', max_length=255, null=True)),
                ('condition_6', models.CharField(db_column='Condition_6', max_length=255, null=True)),
                ('condition_7', models.CharField(db_column='Condition_7', max_length=255, null=True)),
                ('condition_8', models.CharField(db_column='Condition_8', max_length=255, null=True)),
                ('condition_9', models.CharField(db_column='Condition_9', max_length=255, null=True)),
                ('condition_10', models.CharField(db_column='Condition_10', max_length=255, null=True)),
            ],
            options={
                'db_table': 'patient_health',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatientVitals',
            fields=[
                ('patient', models.OneToOneField(db_column='Patient_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='web_app.patientid')),
                ('last_height', models.DecimalField(db_column='Last_height', decimal_places=5, max_digits=10, null=True)),
                ('last_weight', models.DecimalField(db_column='Last_weight', decimal_places=5, max_digits=10, null=True)),
                ('last_heartrate', models.IntegerField(db_column='Last_heartrate', null=True)),
                ('last_systolic_bp', models.IntegerField(db_column='Last_systolic_BP', null=True)),
                ('last_diastolic_bp', models.IntegerField(db_column='Last_diastolic_BP', null=True)),
            ],
            options={
                'db_table': 'patient_vitals',
                'managed': False,
            },
        ),
    ]
