# Generated by Django 4.1 on 2023-04-13 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctors',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='patientcontact',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='patientdoctors',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='patientfinance',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='patienthealth',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='patientid',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='patientvitals',
            options={'managed': True},
        ),
    ]
